package org.powerscala

import org.powerscala.enum.{Enumerated, EnumEntry}

/**
 * @author Matt Hicks <mhicks@powerscala.org>
 */
sealed abstract class Country(val fullName: String) extends EnumEntry {
  override def toString = fullName
}

object Country extends Enumerated[Country] {
  case object US extends Country("United States of America")
  case object CA extends Country("Canada")
  case object GB extends Country("United Kingdom")
  case object AF extends Country("Afghanistan")
  case object AO extends Country("Angola")
  case object AI extends Country("Anguilla")
  case object AG extends Country("Antigua")
  case object AR extends Country("Argentina")
  case object AW extends Country("Aruba")
  case object AU extends Country("Australia")
  case object AT extends Country("Austria")
  case object BS extends Country("Bahamas")
  case object BH extends Country("Bahrain")
  case object BD extends Country("Bangladesh")
  case object BB extends Country("Barbados")
  case object BE extends Country("Belgium")
  case object BM extends Country("Bermuda")
  case object BO extends Country("Bolivia")
  case object XB extends Country("Bonaire")
  case object BA extends Country("Bosnia and Herzegovina")
  case object BW extends Country("Botswana")
  case object BR extends Country("Brazil")
  case object BG extends Country("Bulgaria")
  case object KY extends Country("Cayman Islands")
  case object CL extends Country("Chile")
  case object CN extends Country("China")
  case object CO extends Country("Colombia")
  case object CR extends Country("Costa Rica")
  case object CI extends Country("Cote d'Ivoire")
  case object HR extends Country("Croatia")
  case object XC extends Country("Curacao")
  case object CY extends Country("Cyprus")
  case object CZ extends Country("Czech Republic")
  case object DK extends Country("Denmark")
  case object DM extends Country("Dominica")
  case object DO extends Country("Dominican Republic")
  case object EC extends Country("Ecuador")
  case object EG extends Country("Egypt")
  case object SV extends Country("El Salvador")
  case object EE extends Country("Estonia")
  case object FJ extends Country("Fiji")
  case object FI extends Country("Finland")
  case object FR extends Country("France")
  case object GA extends Country("Gabon")
  case object DE extends Country("Germany")
  case object GR extends Country("Greece")
  case object GD extends Country("Grenada")
  case object GP extends Country("Guadeloupe")
  case object GU extends Country("Guam")
  case object GT extends Country("Guatemala")
  case object GY extends Country("Guyana (British)")
  case object GF extends Country("Guyana (French)")
  case object HT extends Country("Haiti")
  case object HN extends Country("Honduras")
  case object HK extends Country("Hong Kong")
  case object HU extends Country("Hungary")
  case object IS extends Country("Iceland")
  case object IN extends Country("India")
  case object ID extends Country("Indonesia")
  case object IR extends Country("Iran")
  case object IQ extends Country("Iraq")
  case object IE extends Country("Ireland, Republic Of")
  case object IL extends Country("Israel")
  case object IT extends Country("Italy")
  case object JM extends Country("Jamaica")
  case object JP extends Country("Japan")
  case object JO extends Country("Jordan")
  case object KZ extends Country("Kazakhstan")
  case object KR extends Country("Korea, Republic Of")
  case object KW extends Country("Kuwait")
  case object LV extends Country("Latvia")
  case object LB extends Country("Lebanon")
  case object LS extends Country("Lesotho")
  case object LT extends Country("Lithuania")
  case object LU extends Country("Luxembourg")
  case object MY extends Country("Malaysia")
  case object MT extends Country("Malta")
  case object MQ extends Country("Martinique")
  case object MU extends Country("Mauritius")
  case object MX extends Country("Mexico")
  case object MS extends Country("Montserrat")
  case object MZ extends Country("Mozambique")
  case object NP extends Country("Nepal")
  case object NL extends Country("Netherlands")
  case object XN extends Country("Nevis")
  case object NZ extends Country("New Zealand")
  case object NI extends Country("Nicaragua")
  case object NG extends Country("Nigeria")
  case object NO extends Country("Norway")
  case object OM extends Country("Oman")
  case object PK extends Country("Pakistan")
  case object PA extends Country("Panama")
  case object PG extends Country("Papua New Guinea")
  case object PY extends Country("Paraguay")
  case object PE extends Country("Peru")
  case object PH extends Country("Philippines")
  case object PL extends Country("Poland")
  case object PT extends Country("Portugal")
  case object PR extends Country("Puerto Rico")
  case object QA extends Country("Qatar")
  case object UG extends Country("Republic of Uganda")
  case object RE extends Country("Reunion Islands")
  case object RO extends Country("Romania")
  case object RU extends Country("Russian Federation The")
  case object SA extends Country("Saudi Arabia")
  case object RS extends Country("Serbia")
  case object SC extends Country("Seychelles")
  case object SG extends Country("Singapore")
  case object SK extends Country("Slovak Republic")
  case object SI extends Country("Slovenia")
  case object ZA extends Country("South Africa")
  case object ES extends Country("Spain")
  case object LK extends Country("Sri Lanka")
  case object XY extends Country("St Barthelem")
  case object XE extends Country("St Eustatius")
  case object KN extends Country("St Kitts")
  case object LC extends Country("St Lucia")
  case object VC extends Country("St Vincent")
  case object XM extends Country("St. Maarten")
  case object SR extends Country("Suriname")
  case object SE extends Country("Sweden")
  case object CH extends Country("Switzerland")
  case object TW extends Country("Taiwan")
  case object ZZ extends Country("Test Country")
  case object TH extends Country("Thailand")
  case object TT extends Country("Trinidad and Tobago")
  case object TR extends Country("Turkey")
  case object TC extends Country("Turks and Caicos Islands")
  case object UA extends Country("Ukraine")
  case object AE extends Country("United Arab Emirates")
  case object TZ extends Country("United Republic of Tanzania")
  case object UY extends Country("Uruguay")
  case object VE extends Country("Venezuela")
  case object VN extends Country("Vietnam")
  case object VG extends Country("Virgin Islands (British)")
  case object VI extends Country("Virgin Islands (US)")
  case object ZM extends Country("Zambia")
  case object ZW extends Country("Zimbabwe")

  val values = findValues.toVector
}