package org.powerscala

import org.powerscala.enum.{Enumerated, EnumEntry}

/**
 * @author Matt Hicks <mhicks@powerscala.org>
 */
sealed class Currency(val description: String) extends EnumEntry {
  override def toString = "%s (%s)".format(description, name)
}

object Currency extends Enumerated[Currency] {
  case object USD extends Currency("United States dollar")
  case object CAD extends Currency("Canadian dollar")
  case object EUR extends Currency("Euro")
  case object GBP extends Currency("British pound")
  case object AFN extends Currency("Afghan afghani")
  case object ALL extends Currency("Albanian lek")
  case object DZD extends Currency("Algerian dinar")
  case object AOA extends Currency("Angolan kwanza")
  case object ARS extends Currency("Argentine peso")
  case object AMD extends Currency("Armenian dram")
  case object AWG extends Currency("Aruban florin")
  case object AUD extends Currency("Australian dollar")
  case object AZN extends Currency("Azerbaijani manat")
  case object BSD extends Currency("Bahamian dollar")
  case object BHD extends Currency("Bahraini dinar")
  case object BDT extends Currency("Bangladeshi taka")
  case object BBD extends Currency("Barbadian dollar")
  case object BYR extends Currency("Belarusian ruble")
  case object BZD extends Currency("Belize dollar")
  case object BMD extends Currency("Bermudian dollar")
  case object BTN extends Currency("Bhutanese ngultrum")
  case object BOB extends Currency("Bolivian boliviano")
  case object BAM extends Currency("Bosnia and Herzegovina convertible mark")
  case object BWP extends Currency("Botswana pula")
  case object BRL extends Currency("Brazilian real")
  case object BND extends Currency("Brunei dollar")
  case object BGN extends Currency("Bulgarian lev")
  case object MMK extends Currency("Burmese kyat")
  case object BIF extends Currency("Burundian franc")
  case object XPF extends Currency("CFP franc")
  case object KHR extends Currency("Cambodian riel")
  case object CVE extends Currency("Cape Verdean escudo")
  case object KYD extends Currency("Cayman Islands dollar")
  case object XAF extends Currency("Central African CFA franc")
  case object CLP extends Currency("Chilean peso")
  case object CNY extends Currency("Chinese yuan")
  case object COP extends Currency("Colombian peso")
  case object KMF extends Currency("Comorian franc")
  case object CDF extends Currency("Congolese franc")
  case object CRC extends Currency("Costa Rican colón")
  case object HRK extends Currency("Croatian kuna")
  case object CUC extends Currency("Cuban convertible peso")
  case object CUP extends Currency("Cuban peso")
  case object CZK extends Currency("Czech koruna")
  case object DKK extends Currency("Danish krone")
  case object DJF extends Currency("Djiboutian franc")
  case object DOP extends Currency("Dominican peso")
  case object XCD extends Currency("East Caribbean dollar")
  case object EGP extends Currency("Egyptian pound")
  case object ERN extends Currency("Eritrean nakfa")
  case object ETB extends Currency("Ethiopian birr")
  case object FKP extends Currency("Falkland Islands pound")
  case object FJD extends Currency("Fijian dollar")
  case object GMD extends Currency("Gambian dalasi")
  case object GEL extends Currency("Georgian lari")
  case object GHS extends Currency("Ghana cedi")
  case object GIP extends Currency("Gibraltar pound")
  case object GTQ extends Currency("Guatemalan quetzal")
  case object GNF extends Currency("Guinean franc")
  case object GYD extends Currency("Guyanese dollar")
  case object HTG extends Currency("Haitian gourde")
  case object HNL extends Currency("Honduran lempira")
  case object HKD extends Currency("Hong Kong dollar")
  case object HUF extends Currency("Hungarian forint")
  case object ISK extends Currency("Icelandic króna")
  case object INR extends Currency("Indian rupee")
  case object IDR extends Currency("Indonesian rupiah")
  case object IRR extends Currency("Iranian rial")
  case object IQD extends Currency("Iraqi dinar")
  case object ILS extends Currency("Israeli new shekel")
  case object JMD extends Currency("Jamaican dollar")
  case object JPY extends Currency("Japanese yen")
  case object KZT extends Currency("Kazakhstani tenge")
  case object KES extends Currency("Kenyan shilling")
  case object KWD extends Currency("Kuwaiti dinar")
  case object KGS extends Currency("Kyrgyzstani som")
  case object LAK extends Currency("Lao kip")
  case object LVL extends Currency("Latvian lats")
  case object LBP extends Currency("Lebanese pound")
  case object LSL extends Currency("Lesotho loti")
  case object LRD extends Currency("Liberian dollar")
  case object LYD extends Currency("Libyan dinar")
  case object LTL extends Currency("Lithuanian litas")
  case object MOP extends Currency("Macanese pataca")
  case object MKD extends Currency("Macedonian denar")
  case object MGA extends Currency("Malagasy ariary")
  case object MWK extends Currency("Malawian kwacha")
  case object MYR extends Currency("Malaysian ringgit")
  case object MVR extends Currency("Maldivian rufiyaa")
  case object MRO extends Currency("Mauritanian ouguiya")
  case object MUR extends Currency("Mauritian rupee")
  case object MXN extends Currency("Mexican peso")
  case object MDL extends Currency("Moldovan leu")
  case object MNT extends Currency("Mongolian tögrög")
  case object MAD extends Currency("Moroccan dirham")
  case object MZN extends Currency("Mozambican metical")
  case object NAD extends Currency("Namibian dollar")
  case object NPR extends Currency("Nepalese rupee")
  case object ANG extends Currency("Netherlands Antillean guilder")
  case object TWD extends Currency("New Taiwan dollar")
  case object NZD extends Currency("New Zealand dollar")
  case object NIO extends Currency("Nicaraguan córdoba")
  case object NGN extends Currency("Nigerian naira")
  case object KPW extends Currency("North Korean won")
  case object NOK extends Currency("Norwegian krone")
  case object OMR extends Currency("Omani rial")
  case object PKR extends Currency("Pakistani rupee")
  case object PAB extends Currency("Panamanian balboa")
  case object PGK extends Currency("Papua New Guinean kina")
  case object PYG extends Currency("Paraguayan guaraní")
  case object PEN extends Currency("Peruvian nuevo sol")
  case object PHP extends Currency("Philippine peso")
  case object PLN extends Currency("Polish złoty")
  case object QAR extends Currency("Qatari riyal")
  case object RON extends Currency("Romanian leu")
  case object RUB extends Currency("Russian ruble")
  case object RWF extends Currency("Rwandan franc")
  case object SHP extends Currency("Saint Helena pound")
  case object SVC extends Currency("Salvadoran colón")
  case object WST extends Currency("Samoan tālā")
  case object SAR extends Currency("Saudi riyal")
  case object RSD extends Currency("Serbian dinar")
  case object SCR extends Currency("Seychellois rupee")
  case object SLL extends Currency("Sierra Leonean leone")
  case object SGD extends Currency("Singapore dollar")
  case object SBD extends Currency("Solomon Islands dollar")
  case object SOS extends Currency("Somali shilling")
  case object ZAR extends Currency("South African rand")
  case object KRW extends Currency("South Korean won")
  case object SSP extends Currency("South Sudanese pound")
  case object LKR extends Currency("Sri Lankan rupee")
  case object SDG extends Currency("Sudanese pound")
  case object SRD extends Currency("Surinamese dollar")
  case object SZL extends Currency("Swazi lilangeni")
  case object SEK extends Currency("Swedish krona")
  case object CHF extends Currency("Swiss franc")
  case object SYP extends Currency("Syrian pound")
  case object STD extends Currency("São Tomé and Príncipe dobra")
  case object TJS extends Currency("Tajikistani somoni")
  case object TZS extends Currency("Tanzanian shilling")
  case object THB extends Currency("Thai baht")
  case object TOP extends Currency("Tongan paʻanga")
  case object TTD extends Currency("Trinidad and Tobago dollar")
  case object TND extends Currency("Tunisian dinar")
  case object TRY extends Currency("Turkish lira")
  case object TMT extends Currency("Turkmenistan manat")
  case object UGX extends Currency("Ugandan shilling")
  case object UAH extends Currency("Ukrainian hryvnia")
  case object AED extends Currency("United Arab Emirates dirham")
  case object UYU extends Currency("Uruguayan peso")
  case object UZS extends Currency("Uzbekistani som")
  case object VUV extends Currency("Vanuatu vatu")
  case object VEF extends Currency("Venezuelan bolívar")
  case object VND extends Currency("Vietnamese đồng")
  case object XOF extends Currency("West African CFA franc")
  case object YER extends Currency("Yemeni rial")
  case object ZMK extends Currency("Zambian kwacha")
  case object ZWL extends Currency("Zimbabwean dollar")

  val values = findValues.toVector
}