package org.powerscala

import enumeratum._

sealed abstract class Language(val bibliographic: String,
                      val terminology: String,
                      val iso639_1: Option[String],
                      val englishNames: List[String],
                      val frenchNames: List[String],
                      val germanNames: List[String]) extends EnumEntry {
  Language.init(this)
}

object Language extends Enum[Language] {
  private var lookup = Map.empty[String, Language]

  case object Abkhazian extends Language("abk", "abk", Some("ab"), List("Abkhazian"), List("abkhaze"), List("Abchasisch"))
  case object Achinese extends Language("ace", "ace", None, List("Achinese"), List("aceh"), List("Aceh-Sprache"))
  case object Acoli extends Language("ach", "ach", None, List("Acoli"), List("acoli"), List("Acholi-Sprache"))
  case object Adangme extends Language("ada", "ada", None, List("Adangme"), List("adangme"), List("Adangme-Sprache"))
  case object Adyghe extends Language("ady", "ady", None, List("Adyghe", "Adygei"), List("adyghé"), List("Adygisch"))
  case object Afar extends Language("aar", "aar", Some("aa"), List("Afar"), List("afar"), List("Danakil-Sprache"))
  case object Afrihili extends Language("afh", "afh", None, List("Afrihili"), List("afrihili"), List("Afrihili"))
  case object Afrikaans extends Language("afr", "afr", Some("af"), List("Afrikaans"), List("afrikaans"), List("Afrikaans"))
  case object AfroAsiaticLanguages extends Language("afa", "afa", None, List("Afro-Asiatic languages"), List("afro-asiatiques, langues"), List("Hamitosemitische Sprachen (Andere)"))
  case object Ainu extends Language("ain", "ain", None, List("Ainu"), List("aïnou"), List("Ainu-Sprache"))
  case object Akan extends Language("aka", "aka", Some("ak"), List("Akan"), List("akan"), List("Akan-Sprache"))
  case object Akkadian extends Language("akk", "akk", None, List("Akkadian"), List("akkadien"), List("Akkadisch"))
  case object Albanian extends Language("alb", "sqi", Some("sq"), List("Albanian"), List("albanais"), List("Albanisch"))
  case object Aleut extends Language("ale", "ale", None, List("Aleut"), List("aléoute"), List("Aleutisch"))
  case object AlgonquianLanguages extends Language("alg", "alg", None, List("Algonquian languages"), List("algonquines, langues"), List("Algonkin-Sprachen (Andere)"))
  case object AltaicLanguages extends Language("tut", "tut", None, List("Altaic languages"), List("altaïques, langues"), List("Altaische Sprachen (Andere)"))
  case object Amharic extends Language("amh", "amh", Some("am"), List("Amharic"), List("amharique"), List("Amharisch"))
  case object Angika extends Language("anp", "anp", None, List("Angika"), List("angika"), List("Anga-Sprache"))
  case object ApacheLanguages extends Language("apa", "apa", None, List("Apache languages"), List("apaches, langues"), List("Apachen-Sprachen"))
  case object Arabic extends Language("ara", "ara", Some("ar"), List("Arabic"), List("arabe"), List("Arabisch"))
  case object Aragonese extends Language("arg", "arg", Some("an"), List("Aragonese"), List("aragonais"), List("Aragonesisch"))
  case object Arapaho extends Language("arp", "arp", None, List("Arapaho"), List("arapaho"), List("Arapaho-Sprache"))
  case object Arawak extends Language("arw", "arw", None, List("Arawak"), List("arawak"), List("Arawak-Sprachen"))
  case object Armenian extends Language("arm", "hye", Some("hy"), List("Armenian"), List("arménien"), List("Armenisch"))
  case object Aromanian extends Language("rup", "rup", None, List("Aromanian", "Arumanian", "Macedo-Romanian"), List("aroumain", "macédo-roumain"), List("Aromunisch"))
  case object ArtificialLanguages extends Language("art", "art", None, List("Artificial languages"), List("artificielles, langues"), List("Kunstsprachen (Andere)"))
  case object Assamese extends Language("asm", "asm", Some("as"), List("Assamese"), List("assamais"), List("Assamesisch"))
  case object Asturian extends Language("ast", "ast", None, List("Asturian", "Bable", "Leonese", "Asturleonese"), List("asturien", "bable", "léonais", "asturoléonais"), List("Asturisch"))
  case object AthapascanLanguages extends Language("ath", "ath", None, List("Athapascan languages"), List("athapascanes, langues"), List("Athapaskische Sprachen (Andere)"))
  case object AustralianLanguages extends Language("aus", "aus", None, List("Australian languages"), List("australiennes, langues"), List("Australische Sprachen"))
  case object AustronesianLanguages extends Language("map", "map", None, List("Austronesian languages"), List("austronésiennes, langues"), List("Austronesische Sprachen (Andere)"))
  case object Avaric extends Language("ava", "ava", Some("av"), List("Avaric"), List("avar"), List("Awarisch"))
  case object Avestan extends Language("ave", "ave", Some("ae"), List("Avestan"), List("avestique"), List("Avestisch"))
  case object Awadhi extends Language("awa", "awa", None, List("Awadhi"), List("awadhi"), List("Awadhi"))
  case object Aymara extends Language("aym", "aym", Some("ay"), List("Aymara"), List("aymara"), List("Aymará-Sprache"))
  case object Azerbaijani extends Language("aze", "aze", Some("az"), List("Azerbaijani"), List("azéri"), List("Aserbeidschanisch"))
  case object Balinese extends Language("ban", "ban", None, List("Balinese"), List("balinais"), List("Balinesisch"))
  case object BalticLanguages extends Language("bat", "bat", None, List("Baltic languages"), List("baltes, langues"), List("Baltische Sprachen (Andere)"))
  case object Baluchi extends Language("bal", "bal", None, List("Baluchi"), List("baloutchi"), List("Belutschisch"))
  case object Bambara extends Language("bam", "bam", Some("bm"), List("Bambara"), List("bambara"), List("Bambara-Sprache"))
  case object BamilekeLanguages extends Language("bai", "bai", None, List("Bamileke languages"), List("bamiléké, langues"), List("Bamileke-Sprachen"))
  case object BandaLanguages extends Language("bad", "bad", None, List("Banda languages"), List("banda, langues"), List("Banda-Sprachen (Ubangi-Sprachen)"))
  case object BantuLanguages extends Language("bnt", "bnt", None, List("Bantu languages"), List("bantou, langues"), List("Bantusprachen (Andere)"))
  case object Basa extends Language("bas", "bas", None, List("Basa"), List("basa"), List("Basaa-Sprache"))
  case object Bashkir extends Language("bak", "bak", Some("ba"), List("Bashkir"), List("bachkir"), List("Baschkirisch"))
  case object Basque extends Language("baq", "eus", Some("eu"), List("Basque"), List("basque"), List("Baskisch"))
  case object BatakLanguages extends Language("btk", "btk", None, List("Batak languages"), List("batak, langues"), List("Batak-Sprache"))
  case object Beja extends Language("bej", "bej", None, List("Beja", "Bedawiyet"), List("bedja"), List("Bedauye"))
  case object Belarusian extends Language("bel", "bel", Some("be"), List("Belarusian"), List("biélorusse"), List("Weißrussisch"))
  case object Bemba extends Language("bem", "bem", None, List("Bemba"), List("bemba"), List("Bemba-Sprache"))
  case object Bengali extends Language("ben", "ben", Some("bn"), List("Bengali"), List("bengali"), List("Bengali"))
  case object BerberLanguages extends Language("ber", "ber", None, List("Berber languages"), List("berbères, langues"), List("Berbersprachen (Andere)"))
  case object Bhojpuri extends Language("bho", "bho", None, List("Bhojpuri"), List("bhojpuri"), List("Bhojpuri"))
  case object BihariLanguages extends Language("bih", "bih", Some("bh"), List("Bihari languages"), List("langues biharis"), List("Bihari (Andere)"))
  case object Bikol extends Language("bik", "bik", None, List("Bikol"), List("bikol"), List("Bikol-Sprache"))
  case object Bini extends Language("bin", "bin", None, List("Bini", "Edo"), List("bini", "edo"), List("Edo-Sprache"))
  case object Bislama extends Language("bis", "bis", Some("bi"), List("Bislama"), List("bichlamar"), List("Beach-la-mar"))
  case object Blin extends Language("byn", "byn", None, List("Blin", "Bilin"), List("blin", "bilen"), List("Bilin-Sprache"))
  case object Blissymbols extends Language("zbl", "zbl", None, List("Blissymbols", "Blissymbolics", "Bliss"), List("symboles Bliss", "Bliss"), List("Bliss-Symbol"))
  case object BokmålNorwegian extends Language("nob", "nob", Some("nb"), List("Bokmål, Norwegian", "Norwegian Bokmål"), List("norvégien bokmål"), List("Bokmål"))
  case object Bosnian extends Language("bos", "bos", Some("bs"), List("Bosnian"), List("bosniaque"), List("Bosnisch"))
  case object Braj extends Language("bra", "bra", None, List("Braj"), List("braj"), List("Braj-Bhakha"))
  case object Breton extends Language("bre", "bre", Some("br"), List("Breton"), List("breton"), List("Bretonisch"))
  case object Buginese extends Language("bug", "bug", None, List("Buginese"), List("bugi"), List("Bugi-Sprache"))
  case object Bulgarian extends Language("bul", "bul", Some("bg"), List("Bulgarian"), List("bulgare"), List("Bulgarisch"))
  case object Buriat extends Language("bua", "bua", None, List("Buriat"), List("bouriate"), List("Burjatisch"))
  case object Burmese extends Language("bur", "mya", Some("my"), List("Burmese"), List("birman"), List("Birmanisch"))
  case object Caddo extends Language("cad", "cad", None, List("Caddo"), List("caddo"), List("Caddo-Sprachen"))
  case object Catalan extends Language("cat", "cat", Some("ca"), List("Catalan", "Valencian"), List("catalan", "valencien"), List("Katalanisch"))
  case object CaucasianLanguages extends Language("cau", "cau", None, List("Caucasian languages"), List("caucasiennes, langues"), List("Kaukasische Sprachen (Andere)"))
  case object Cebuano extends Language("ceb", "ceb", None, List("Cebuano"), List("cebuano"), List("Cebuano"))
  case object CelticLanguages extends Language("cel", "cel", None, List("Celtic languages"), List("celtiques, langues", "celtes, langues"), List("Keltische Sprachen (Andere)"))
  case object CentralAmericanIndianLanguages extends Language("cai", "cai", None, List("Central American Indian languages"), List("amérindiennes de l'Amérique centrale, langues"), List("Indianersprachen, Zentralamerika (Andere)"))
  case object CentralKhmer extends Language("khm", "khm", Some("km"), List("Central Khmer"), List("khmer central"), List("Kambodschanisch"))
  case object Chagatai extends Language("chg", "chg", None, List("Chagatai"), List("djaghataï"), List("Tschagataisch"))
  case object ChamicLanguages extends Language("cmc", "cmc", None, List("Chamic languages"), List("chames, langues"), List("Cham-Sprachen"))
  case object Chamorro extends Language("cha", "cha", Some("ch"), List("Chamorro"), List("chamorro"), List("Chamorro-Sprache"))
  case object Chechen extends Language("che", "che", Some("ce"), List("Chechen"), List("tchétchène"), List("Tschetschenisch"))
  case object Cherokee extends Language("chr", "chr", None, List("Cherokee"), List("cherokee"), List("Cherokee-Sprache"))
  case object Cheyenne extends Language("chy", "chy", None, List("Cheyenne"), List("cheyenne"), List("Cheyenne-Sprache"))
  case object Chibcha extends Language("chb", "chb", None, List("Chibcha"), List("chibcha"), List("Chibcha-Sprachen"))
  case object Chichewa extends Language("nya", "nya", Some("ny"), List("Chichewa", "Chewa", "Nyanja"), List("chichewa", "chewa", "nyanja"), List("Nyanja-Sprache"))
  case object Chinese extends Language("chi", "zho", Some("zh"), List("Chinese", "Mandarin"), List("chinois"), List("Chinesisch"))
  case object ChinookJargon extends Language("chn", "chn", None, List("Chinook jargon"), List("chinook, jargon"), List("Chinook-Jargon"))
  case object Chipewyan extends Language("chp", "chp", None, List("Chipewyan", "Dene Suline"), List("chipewyan"), List("Chipewyan-Sprache"))
  case object Choctaw extends Language("cho", "cho", None, List("Choctaw"), List("choctaw"), List("Choctaw-Sprache"))
  case object ChurchSlavic extends Language("chu", "chu", Some("cu"), List("Church Slavic", "Old Slavonic", "Church Slavonic", "Old Bulgarian", "Old Church Slavonic"), List("slavon d'église", "vieux slave", "slavon liturgique", "vieux bulgare"), List("Kirchenslawisch"))
  case object Chuukese extends Language("chk", "chk", None, List("Chuukese"), List("chuuk"), List("Trukesisch"))
  case object Chuvash extends Language("chv", "chv", Some("cv"), List("Chuvash"), List("tchouvache"), List("Tschuwaschisch"))
  case object ClassicalNewari extends Language("nwc", "nwc", None, List("Classical Newari", "Old Newari", "Classical Nepal Bhasa"), List("newari classique"), List("Alt-Newari"))
  case object ClassicalSyriac extends Language("syc", "syc", None, List("Classical Syriac"), List("syriaque classique"), List("Syrisch"))
  case object Coptic extends Language("cop", "cop", None, List("Coptic"), List("copte"), List("Koptisch"))
  case object Cornish extends Language("cor", "cor", Some("kw"), List("Cornish"), List("cornique"), List("Kornisch"))
  case object Corsican extends Language("cos", "cos", Some("co"), List("Corsican"), List("corse"), List("Korsisch"))
  case object Cree extends Language("cre", "cre", Some("cr"), List("Cree"), List("cree"), List("Cree-Sprache"))
  case object Creek extends Language("mus", "mus", None, List("Creek"), List("muskogee"), List("Muskogisch"))
  case object CreolesAndPidgins extends Language("crp", "crp", None, List("Creoles and pidgins"), List("créoles et pidgins"), List("Kreolische Sprachen", "Pidginsprachen (Andere)"))
  case object CreolesAndPidginsEnglishBased extends Language("cpe", "cpe", None, List("Creoles and pidgins, English based"), List("créoles et pidgins basés sur l'anglais"), List("Kreolisch-Englisch (Andere)"))
  case object CreolesAndPidginsFrenchBased extends Language("cpf", "cpf", None, List("Creoles and pidgins, French-based"), List("créoles et pidgins basés sur le français"), List("Kreolisch-Französisch (Andere)"))
  case object CreolesAndPidginsPortugueseBased extends Language("cpp", "cpp", None, List("Creoles and pidgins, Portuguese-based"), List("créoles et pidgins basés sur le portugais"), List("Kreolisch-Portugiesisch (Andere)"))
  case object CrimeanTatar extends Language("crh", "crh", None, List("Crimean Tatar", "Crimean Turkish"), List("tatar de Crimé"), List("Krimtatarisch"))
  case object Croatian extends Language("hrv", "hrv", Some("hr"), List("Croatian"), List("croate"), List("Kroatisch"))
  case object CushiticLanguages extends Language("cus", "cus", None, List("Cushitic languages"), List("couchitiques, langues"), List("Kuschitische Sprachen (Andere)"))
  case object Czech extends Language("cze", "ces", Some("cs"), List("Czech"), List("tchèque"), List("Tschechisch"))
  case object Dakota extends Language("dak", "dak", None, List("Dakota"), List("dakota"), List("Dakota-Sprache"))
  case object Danish extends Language("dan", "dan", Some("da"), List("Danish"), List("danois"), List("Dänisch"))
  case object Dargwa extends Language("dar", "dar", None, List("Dargwa"), List("dargwa"), List("Darginisch"))
  case object Delaware extends Language("del", "del", None, List("Delaware"), List("delaware"), List("Delaware-Sprache"))
  case object Dinka extends Language("din", "din", None, List("Dinka"), List("dinka"), List("Dinka-Sprache"))
  case object Divehi extends Language("div", "div", Some("dv"), List("Divehi", "Dhivehi", "Maldivian"), List("maldivien"), List("Maledivisch"))
  case object Dogri extends Language("doi", "doi", None, List("Dogri"), List("dogri"), List("Dogri"))
  case object Dogrib extends Language("dgr", "dgr", None, List("Dogrib"), List("dogrib"), List("Dogrib-Sprache"))
  case object DravidianLanguages extends Language("dra", "dra", None, List("Dravidian languages"), List("dravidiennes, langues"), List("Drawidische Sprachen (Andere)"))
  case object Duala extends Language("dua", "dua", None, List("Duala"), List("douala"), List("Duala-Sprachen"))
  case object Dutch extends Language("dut", "nld", Some("nl"), List("Dutch", "Flemish"), List("néerlandais", "flamand"), List("Niederländisch"))
  case object DutchMiddle extends Language("dum", "dum", None, List("Dutch, Middle (ca.1050-1350)"), List("néerlandais moyen (ca. 1050-1350)"), List("Mittelniederländisch"))
  case object Dyula extends Language("dyu", "dyu", None, List("Dyula"), List("dioula"), List("Dyula-Sprache"))
  case object Dzongkha extends Language("dzo", "dzo", Some("dz"), List("Dzongkha"), List("dzongkha"), List("Dzongkha"))
  case object EasternFrisian extends Language("frs", "frs", None, List("Eastern Frisian"), List("frison oriental"), List("Ostfriesisch"))
  case object Efik extends Language("efi", "efi", None, List("Efik"), List("efik"), List("Efik"))
  case object Egyptian extends Language("egy", "egy", None, List("Egyptian (Ancient)"), List("égyptien"), List("Ägyptisch"))
  case object Ekajuk extends Language("eka", "eka", None, List("Ekajuk"), List("ekajuk"), List("Ekajuk"))
  case object Elamite extends Language("elx", "elx", None, List("Elamite"), List("élamite"), List("Elamisch"))
  case object English extends Language("eng", "eng", Some("en"), List("English"), List("anglais"), List("Englisch"))
  case object EnglishMiddle extends Language("enm", "enm", None, List("English, Middle (1100-1500)"), List("anglais moyen (1100-1500)"), List("Mittelenglisch"))
  case object EnglishOld extends Language("ang", "ang", None, List("English, Old (ca.450-1100)"), List("anglo-saxon (ca.450-1100)"), List("Altenglisch"))
  case object Erzya extends Language("myv", "myv", None, List("Erzya"), List("erza"), List("Erza-Mordwinisch"))
  case object Esperanto extends Language("epo", "epo", Some("eo"), List("Esperanto"), List("espéranto"), List("Esperanto"))
  case object Estonian extends Language("est", "est", Some("et"), List("Estonian"), List("estonien"), List("Estnisch"))
  case object Ewe extends Language("ewe", "ewe", Some("ee"), List("Ewe"), List("éwé"), List("Ewe-Sprache"))
  case object Ewondo extends Language("ewo", "ewo", None, List("Ewondo"), List("éwondo"), List("Ewondo"))
  case object Fang extends Language("fan", "fan", None, List("Fang"), List("fang"), List("Pangwe-Sprache"))
  case object Fanti extends Language("fat", "fat", None, List("Fanti"), List("fanti"), List("Fante-Sprache"))
  case object Faroese extends Language("fao", "fao", Some("fo"), List("Faroese"), List("féroïen"), List("Färöisch"))
  case object Fijian extends Language("fij", "fij", Some("fj"), List("Fijian"), List("fidjien"), List("Fidschi-Sprache"))
  case object Filipino extends Language("fil", "fil", None, List("Filipino", "Pilipino"), List("filipino", "pilipino"), List("Pilipino"))
  case object Finnish extends Language("fin", "fin", Some("fi"), List("Finnish"), List("finnois"), List("Finnisch"))
  case object FinnoUgrianLanguages extends Language("fiu", "fiu", None, List("Finno-Ugrian languages"), List("finno-ougriennes, langues"), List("Finnougrische Sprachen (Andere)"))
  case object Fon extends Language("fon", "fon", None, List("Fon"), List("fon"), List("Fon-Sprache"))
  case object French extends Language("fre", "fra", Some("fr"), List("French"), List("français"), List("Französisch"))
  case object FrenchMiddle extends Language("frm", "frm", None, List("French, Middle (ca.1400-1600)"), List("français moyen (1400-1600)"), List("Mittelfranzösisch"))
  case object FrenchOld extends Language("fro", "fro", None, List("French, Old (842-ca.1400)"), List("français ancien (842-ca.1400)"), List("Altfranzösisch"))
  case object Friulian extends Language("fur", "fur", None, List("Friulian"), List("frioulan"), List("Friulisch"))
  case object Fulah extends Language("ful", "ful", Some("ff"), List("Fulah"), List("peul"), List("Ful"))
  case object Ga extends Language("gaa", "gaa", None, List("Ga"), List("ga"), List("Ga-Sprache"))
  case object Gaelic extends Language("gla", "gla", Some("gd"), List("Gaelic", "Scottish Gaelic"), List("gaélique", "gaélique écossais"), List("Gälisch-Schottisch"))
  case object GalibiCarib extends Language("car", "car", None, List("Galibi Carib"), List("karib", "galibi", "carib"), List("Karibische Sprachen"))
  case object Galician extends Language("glg", "glg", Some("gl"), List("Galician"), List("galicien"), List("Galicisch"))
  case object Ganda extends Language("lug", "lug", Some("lg"), List("Ganda"), List("ganda"), List("Ganda-Sprache"))
  case object Gayo extends Language("gay", "gay", None, List("Gayo"), List("gayo"), List("Gayo-Sprache"))
  case object Gbaya extends Language("gba", "gba", None, List("Gbaya"), List("gbaya"), List("Gbaya-Sprache"))
  case object Geez extends Language("gez", "gez", None, List("Geez"), List("guèze"), List("Altäthiopisch"))
  case object Georgian extends Language("geo", "kat", Some("ka"), List("Georgian"), List("géorgien"), List("Georgisch"))
  case object German extends Language("ger", "deu", Some("de"), List("German"), List("allemand"), List("Deutsch"))
  case object GermanMiddleHigh extends Language("gmh", "gmh", None, List("German, Middle High (ca.1050-1500)"), List("allemand, moyen haut (ca. 1050-1500)"), List("Mittelhochdeutsch"))
  case object GermanOldHigh extends Language("goh", "goh", None, List("German, Old High (ca.750-1050)"), List("allemand, vieux haut (ca. 750-1050)"), List("Althochdeutsch"))
  case object GermanicLanguages extends Language("gem", "gem", None, List("Germanic languages"), List("germaniques, langues"), List("Germanische Sprachen (Andere)"))
  case object Gilbertese extends Language("gil", "gil", None, List("Gilbertese"), List("kiribati"), List("Gilbertesisch"))
  case object Gondi extends Language("gon", "gon", None, List("Gondi"), List("gond"), List("Gondi-Sprache"))
  case object Gorontalo extends Language("gor", "gor", None, List("Gorontalo"), List("gorontalo"), List("Gorontalesisch"))
  case object Gothic extends Language("got", "got", None, List("Gothic"), List("gothique"), List("Gotisch"))
  case object Grebo extends Language("grb", "grb", None, List("Grebo"), List("grebo"), List("Grebo-Sprache"))
  case object GreekAncient extends Language("grc", "grc", None, List("Greek, Ancient (to 1453)"), List("grec ancien (jusqu'à 1453)"), List("Griechisch"))
  case object GreekModern extends Language("gre", "ell", Some("el"), List("Greek", "Greek, Modern (1453-)"), List("grec moderne (après 1453)"), List("Neugriechisch"))
  case object Guarani extends Language("grn", "grn", Some("gn"), List("Guarani"), List("guarani"), List("Guaraní-Sprache"))
  case object Gujarati extends Language("guj", "guj", Some("gu"), List("Gujarati"), List("goudjrati"), List("Gujarati-Sprache"))
  case object GwichIn extends Language("gwi", "gwi", None, List("Gwich'in"), List("gwich'in"), List("Kutchin-Sprache"))
  case object Haida extends Language("hai", "hai", None, List("Haida"), List("haida"), List("Haida-Sprache"))
  case object Haitian extends Language("hat", "hat", Some("ht"), List("Haitian", "Haitian Creole"), List("haïtien", "créole haïtien"), List("Haïtien (Haiti-Kreolisch)"))
  case object Hausa extends Language("hau", "hau", Some("ha"), List("Hausa"), List("haoussa"), List("Haussa-Sprache"))
  case object Hawaiian extends Language("haw", "haw", None, List("Hawaiian"), List("hawaïen"), List("Hawaiisch"))
  case object Hebrew extends Language("heb", "heb", Some("he"), List("Hebrew"), List("hébreu"), List("Hebräisch"))
  case object Herero extends Language("her", "her", Some("hz"), List("Herero"), List("herero"), List("Herero-Sprache"))
  case object Hiligaynon extends Language("hil", "hil", None, List("Hiligaynon"), List("hiligaynon"), List("Hiligaynon-Sprache"))
  case object HimachaliLanguages extends Language("him", "him", None, List("Himachali languages", "Western Pahari languages"), List("langues himachalis", "langues paharis occidentales"), List("Himachali"))
  case object Hindi extends Language("hin", "hin", Some("hi"), List("Hindi", "Hindustani"), List("hindi"), List("Hindi"))
  case object HiriMotu extends Language("hmo", "hmo", Some("ho"), List("Hiri Motu"), List("hiri motu"), List("Hiri-Motu"))
  case object Hittite extends Language("hit", "hit", None, List("Hittite"), List("hittite"), List("Hethitisch"))
  case object Hmong extends Language("hmn", "hmn", None, List("Hmong", "Mong"), List("hmong"), List("Miao-Sprachen"))
  case object Hungarian extends Language("hun", "hun", Some("hu"), List("Hungarian"), List("hongrois"), List("Ungarisch"))
  case object Hupa extends Language("hup", "hup", None, List("Hupa"), List("hupa"), List("Hupa-Sprache"))
  case object Iban extends Language("iba", "iba", None, List("Iban"), List("iban"), List("Iban-Sprache"))
  case object Icelandic extends Language("ice", "isl", Some("is"), List("Icelandic"), List("islandais"), List("Isländisch"))
  case object Ido extends Language("ido", "ido", Some("io"), List("Ido"), List("ido"), List("Ido"))
  case object Igbo extends Language("ibo", "ibo", Some("ig"), List("Igbo"), List("igbo"), List("Ibo-Sprache"))
  case object IjoLanguages extends Language("ijo", "ijo", None, List("Ijo languages"), List("ijo, langues"), List("Ijo-Sprache"))
  case object Iloko extends Language("ilo", "ilo", None, List("Iloko"), List("ilocano"), List("Ilokano-Sprache"))
  case object InariSami extends Language("smn", "smn", None, List("Inari Sami"), List("sami d'Inari"), List("Inarisaamisch"))
  case object IndicLanguages extends Language("inc", "inc", None, List("Indic languages"), List("indo-aryennes, langues"), List("Indoarische Sprachen (Andere)"))
  case object IndoEuropeanLanguages extends Language("ine", "ine", None, List("Indo-European languages"), List("indo-européennes, langues"), List("Indogermanische Sprachen (Andere)"))
  case object Indonesian extends Language("ind", "ind", Some("id"), List("Indonesian"), List("indonésien"), List("Bahasa Indonesia"))
  case object Ingush extends Language("inh", "inh", None, List("Ingush"), List("ingouche"), List("Inguschisch"))
  case object Interlingua extends Language("ina", "ina", Some("ia"), List("Interlingua (International Auxiliary Language Association)"), List("interlingua (langue auxiliaire internationale)"), List("Interlingua"))
  case object Interlingue extends Language("ile", "ile", Some("ie"), List("Interlingue", "Occidental"), List("interlingue"), List("Interlingue"))
  case object Inuktitut extends Language("iku", "iku", Some("iu"), List("Inuktitut"), List("inuktitut"), List("Inuktitut"))
  case object Inupiaq extends Language("ipk", "ipk", Some("ik"), List("Inupiaq"), List("inupiaq"), List("Inupik"))
  case object IranianLanguages extends Language("ira", "ira", None, List("Iranian languages"), List("iraniennes, langues"), List("Iranische Sprachen (Andere)"))
  case object Irish extends Language("gle", "gle", Some("ga"), List("Irish"), List("irlandais"), List("Irisch"))
  case object IrishMiddle extends Language("mga", "mga", None, List("Irish, Middle (900-1200)"), List("irlandais moyen (900-1200)"), List("Mittelirisch"))
  case object IrishOld extends Language("sga", "sga", None, List("Irish, Old (to 900)"), List("irlandais ancien (jusqu'à 900)"), List("Altirisch"))
  case object IroquoianLanguages extends Language("iro", "iro", None, List("Iroquoian languages"), List("iroquoises, langues"), List("Irokesische Sprachen"))
  case object Italian extends Language("ita", "ita", Some("it"), List("Italian"), List("italien"), List("Italienisch"))
  case object Japanese extends Language("jpn", "jpn", Some("ja"), List("Japanese"), List("japonais"), List("Japanisch"))
  case object Javanese extends Language("jav", "jav", Some("jv"), List("Javanese"), List("javanais"), List("Javanisch"))
  case object JudeoArabic extends Language("jrb", "jrb", None, List("Judeo-Arabic"), List("judéo-arabe"), List("Jüdisch-Arabisch"))
  case object JudeoPersian extends Language("jpr", "jpr", None, List("Judeo-Persian"), List("judéo-persan"), List("Jüdisch-Persisch"))
  case object Kabardian extends Language("kbd", "kbd", None, List("Kabardian"), List("kabardien"), List("Kabardinisch"))
  case object Kabyle extends Language("kab", "kab", None, List("Kabyle"), List("kabyle"), List("Kabylisch"))
  case object Kachin extends Language("kac", "kac", None, List("Kachin", "Jingpho"), List("kachin", "jingpho"), List("Kachin-Sprache"))
  case object Kalaallisut extends Language("kal", "kal", Some("kl"), List("Kalaallisut", "Greenlandic"), List("groenlandais"), List("Grönländisch"))
  case object Kalmyk extends Language("xal", "xal", None, List("Kalmyk", "Oirat"), List("kalmouk", "oïrat"), List("Kalmückisch"))
  case object Kamba extends Language("kam", "kam", None, List("Kamba"), List("kamba"), List("Kamba-Sprache"))
  case object Kannada extends Language("kan", "kan", Some("kn"), List("Kannada"), List("kannada"), List("Kannada"))
  case object Kanuri extends Language("kau", "kau", Some("kr"), List("Kanuri"), List("kanouri"), List("Kanuri-Sprache"))
  case object KaraKalpak extends Language("kaa", "kaa", None, List("Kara-Kalpak"), List("karakalpak"), List("Karakalpakisch"))
  case object KarachayBalkar extends Language("krc", "krc", None, List("Karachay-Balkar"), List("karatchai balkar"), List("Karatschaiisch-Balkarisch"))
  case object Karelian extends Language("krl", "krl", None, List("Karelian"), List("carélien"), List("Karelisch"))
  case object KarenLanguages extends Language("kar", "kar", None, List("Karen languages"), List("karen, langues"), List("Karenisch"))
  case object Kashmiri extends Language("kas", "kas", Some("ks"), List("Kashmiri"), List("kashmiri"), List("Kaschmiri"))
  case object Kashubian extends Language("csb", "csb", None, List("Kashubian"), List("kachoube"), List("Kaschubisch"))
  case object Kawi extends Language("kaw", "kaw", None, List("Kawi"), List("kawi"), List("Kawi"))
  case object Kazakh extends Language("kaz", "kaz", Some("kk"), List("Kazakh"), List("kazakh"), List("Kasachisch"))
  case object Khasi extends Language("kha", "kha", None, List("Khasi"), List("khasi"), List("Khasi-Sprache"))
  case object KhoisanLanguages extends Language("khi", "khi", None, List("Khoisan languages"), List("khoïsan, langues"), List("Khoisan-Sprachen (Andere)"))
  case object Khotanese extends Language("kho", "kho", None, List("Khotanese", "Sakan"), List("khotanais", "sakan"), List("Sakisch"))
  case object Kikuyu extends Language("kik", "kik", Some("ki"), List("Kikuyu", "Gikuyu"), List("kikuyu"), List("Kikuyu-Sprache"))
  case object Kimbundu extends Language("kmb", "kmb", None, List("Kimbundu"), List("kimbundu"), List("Kimbundu-Sprache"))
  case object Kinyarwanda extends Language("kin", "kin", Some("rw"), List("Kinyarwanda"), List("rwanda"), List("Rwanda-Sprache"))
  case object Kirghiz extends Language("kir", "kir", Some("ky"), List("Kirghiz", "Kyrgyz"), List("kirghiz"), List("Kirgisisch"))
  case object Klingon extends Language("tlh", "tlh", None, List("Klingon", "tlhIngan-Hol"), List("klingon"), List("Klingonisch"))
  case object Komi extends Language("kom", "kom", Some("kv"), List("Komi"), List("kom"), List("Komi-Sprache"))
  case object Kongo extends Language("kon", "kon", Some("kg"), List("Kongo"), List("kongo"), List("Kongo-Sprache"))
  case object Konkani extends Language("kok", "kok", None, List("Konkani"), List("konkani"), List("Konkani"))
  case object Korean extends Language("kor", "kor", Some("ko"), List("Korean"), List("coréen"), List("Koreanisch"))
  case object Kosraean extends Language("kos", "kos", None, List("Kosraean"), List("kosrae"), List("Kosraeanisch"))
  case object Kpelle extends Language("kpe", "kpe", None, List("Kpelle"), List("kpellé"), List("Kpelle-Sprache"))
  case object KruLanguages extends Language("kro", "kro", None, List("Kru languages"), List("krou, langues"), List("Kru-Sprachen (Andere)"))
  case object Kuanyama extends Language("kua", "kua", Some("kj"), List("Kuanyama", "Kwanyama"), List("kuanyama", "kwanyama"), List("Kwanyama-Sprache"))
  case object Kumyk extends Language("kum", "kum", None, List("Kumyk"), List("koumyk"), List("Kumükisch"))
  case object Kurdish extends Language("kur", "kur", Some("ku"), List("Kurdish"), List("kurde"), List("Kurdisch"))
  case object Kurukh extends Language("kru", "kru", None, List("Kurukh"), List("kurukh"), List("Oraon-Sprache"))
  case object Kutenai extends Language("kut", "kut", None, List("Kutenai"), List("kutenai"), List("Kutenai-Sprache"))
  case object Ladino extends Language("lad", "lad", None, List("Ladino"), List("judéo-espagnol"), List("Judenspanisch"))
  case object Lahnda extends Language("lah", "lah", None, List("Lahnda"), List("lahnda"), List("Lahnda"))
  case object Lamba extends Language("lam", "lam", None, List("Lamba"), List("lamba"), List("Lamba-Sprache (Bantusprache)"))
  case object LandDayakLanguages extends Language("day", "day", None, List("Land Dayak languages"), List("dayak, langues"), List("Dajakisch"))
  case object Lao extends Language("lao", "lao", Some("lo"), List("Lao"), List("lao"), List("Laotisch"))
  case object Latin extends Language("lat", "lat", Some("la"), List("Latin"), List("latin"), List("Latein"))
  case object Latvian extends Language("lav", "lav", Some("lv"), List("Latvian"), List("letton"), List("Lettisch"))
  case object Lezghian extends Language("lez", "lez", None, List("Lezghian"), List("lezghien"), List("Lesgisch"))
  case object Limburgan extends Language("lim", "lim", Some("li"), List("Limburgan", "Limburger", "Limburgish"), List("limbourgeois"), List("Limburgisch"))
  case object Lingala extends Language("lin", "lin", Some("ln"), List("Lingala"), List("lingala"), List("Lingala"))
  case object Lithuanian extends Language("lit", "lit", Some("lt"), List("Lithuanian"), List("lituanien"), List("Litauisch"))
  case object Lojban extends Language("jbo", "jbo", None, List("Lojban"), List("lojban"), List("Lojban"))
  case object LowGerman extends Language("nds", "nds", None, List("Low German", "Low Saxon", "German, Low", "Saxon, Low"), List("bas allemand", "bas saxon", "allemand, bas", "saxon, bas"), List("Niederdeutsch"))
  case object LowerSorbian extends Language("dsb", "dsb", None, List("Lower Sorbian"), List("bas-sorabe"), List("Niedersorbisch"))
  case object Lozi extends Language("loz", "loz", None, List("Lozi"), List("lozi"), List("Rotse-Sprache"))
  case object LubaKatanga extends Language("lub", "lub", Some("lu"), List("Luba-Katanga"), List("luba-katanga"), List("Luba-Katanga-Sprache"))
  case object LubaLulua extends Language("lua", "lua", None, List("Luba-Lulua"), List("luba-lulua"), List("Lulua-Sprache"))
  case object Luiseno extends Language("lui", "lui", None, List("Luiseno"), List("luiseno"), List("Luiseño-Sprache"))
  case object LuleSami extends Language("smj", "smj", None, List("Lule Sami"), List("sami de Lule"), List("Lulesaamisch"))
  case object Lunda extends Language("lun", "lun", None, List("Lunda"), List("lunda"), List("Lunda-Sprache"))
  case object Luo extends Language("luo", "luo", None, List("Luo (Kenya and Tanzania)"), List("luo (Kenya et Tanzanie)"), List("Luo-Sprache"))
  case object Lushai extends Language("lus", "lus", None, List("Lushai"), List("lushai"), List("Lushai-Sprache"))
  case object Luxembourgish extends Language("ltz", "ltz", Some("lb"), List("Luxembourgish", "Letzeburgesch"), List("luxembourgeois"), List("Luxemburgisch"))
  case object Macedonian extends Language("mac", "mkd", Some("mk"), List("Macedonian"), List("macédonien"), List("Makedonisch"))
  case object Madurese extends Language("mad", "mad", None, List("Madurese"), List("madourais"), List("Maduresisch"))
  case object Magahi extends Language("mag", "mag", None, List("Magahi"), List("magahi"), List("Khotta"))
  case object Maithili extends Language("mai", "mai", None, List("Maithili"), List("maithili"), List("Maithili"))
  case object Makasar extends Language("mak", "mak", None, List("Makasar"), List("makassar"), List("Makassarisch"))
  case object Malagasy extends Language("mlg", "mlg", Some("mg"), List("Malagasy"), List("malgache"), List("Malagassi-Sprache"))
  case object Malay extends Language("may", "msa", Some("ms"), List("Malay"), List("malais"), List("Malaiisch"))
  case object Malayalam extends Language("mal", "mal", Some("ml"), List("Malayalam"), List("malayalam"), List("Malayalam"))
  case object Maltese extends Language("mlt", "mlt", Some("mt"), List("Maltese"), List("maltais"), List("Maltesisch"))
  case object Manchu extends Language("mnc", "mnc", None, List("Manchu"), List("mandchou"), List("Mandschurisch"))
  case object Mandar extends Language("mdr", "mdr", None, List("Mandar"), List("mandar"), List("Mandaresisch"))
  case object Mandingo extends Language("man", "man", None, List("Mandingo"), List("mandingue"), List("Malinke-Sprache"))
  case object Manipuri extends Language("mni", "mni", None, List("Manipuri"), List("manipuri"), List("Meithei-Sprache"))
  case object ManoboLanguages extends Language("mno", "mno", None, List("Manobo languages"), List("manobo, langues"), List("Manobo-Sprachen"))
  case object Manx extends Language("glv", "glv", Some("gv"), List("Manx"), List("manx", "mannois"), List("Manx"))
  case object Maori extends Language("mao", "mri", Some("mi"), List("Maori"), List("maori"), List("Maori-Sprache"))
  case object Mapudungun extends Language("arn", "arn", None, List("Mapudungun", "Mapuche"), List("mapudungun", "mapuche", "mapuce"), List("Arauka-Sprachen"))
  case object Marathi extends Language("mar", "mar", Some("mr"), List("Marathi"), List("marathe"), List("Marathi"))
  case object Mari extends Language("chm", "chm", None, List("Mari"), List("mari"), List("Tscheremissisch"))
  case object Marshallese extends Language("mah", "mah", Some("mh"), List("Marshallese"), List("marshall"), List("Marschallesisch"))
  case object Marwari extends Language("mwr", "mwr", None, List("Marwari"), List("marvari"), List("Marwari"))
  case object Masai extends Language("mas", "mas", None, List("Masai"), List("massaï"), List("Massai-Sprache"))
  case object MayanLanguages extends Language("myn", "myn", None, List("Mayan languages"), List("maya, langues"), List("Maya-Sprachen"))
  case object Mende extends Language("men", "men", None, List("Mende"), List("mendé"), List("Mende-Sprache"))
  case object MiKmaq extends Language("mic", "mic", None, List("Mi'kmaq", "Micmac"), List("mi'kmaq", "micmac"), List("Micmac-Sprache"))
  case object Minangkabau extends Language("min", "min", None, List("Minangkabau"), List("minangkabau"), List("Minangkabau-Sprache"))
  case object Mirandese extends Language("mwl", "mwl", None, List("Mirandese"), List("mirandais"), List("Mirandesisch"))
  case object Mohawk extends Language("moh", "moh", None, List("Mohawk"), List("mohawk"), List("Mohawk-Sprache"))
  case object Moksha extends Language("mdf", "mdf", None, List("Moksha"), List("moksa"), List("Mokscha-Sprache"))
  case object MonKhmerLanguages extends Language("mkh", "mkh", None, List("Mon-Khmer languages"), List("môn-khmer, langues"), List("Mon-Khmer-Sprachen (Andere)"))
  case object Mongo extends Language("lol", "lol", None, List("Mongo"), List("mongo"), List("Mongo-Sprache"))
  case object Mongolian extends Language("mon", "mon", Some("mn"), List("Mongolian"), List("mongol"), List("Mongolisch"))
  case object Mossi extends Language("mos", "mos", None, List("Mossi"), List("moré"), List("Mossi-Sprache"))
  case object MultipleLanguages extends Language("mul", "mul", None, List("Multiple languages"), List("multilingue"), List("Mehrere Sprachen"))
  case object MundaLanguages extends Language("mun", "mun", None, List("Munda languages"), List("mounda, langues"), List("Mundasprachen (Andere)"))
  case object NKo extends Language("nqo", "nqo", None, List("N'Ko"), List("n'ko"), List("N'Ko"))
  case object NahuatlLanguages extends Language("nah", "nah", None, List("Nahuatl languages"), List("nahuatl, langues"), List("Nahuatl"))
  case object Nauru extends Language("nau", "nau", Some("na"), List("Nauru"), List("nauruan"), List("Nauruanisch"))
  case object Navajo extends Language("nav", "nav", Some("nv"), List("Navajo", "Navaho"), List("navaho"), List("Navajo-Sprache"))
  case object NdebeleNorth extends Language("nde", "nde", Some("nd"), List("Ndebele, North", "North Ndebele"), List("ndébélé du Nord"), List("Ndebele-Sprache (Simbabwe)"))
  case object NdebeleSouth extends Language("nbl", "nbl", Some("nr"), List("Ndebele, South", "South Ndebele"), List("ndébélé du Sud"), List("Ndebele-Sprache (Transvaal)"))
  case object Ndonga extends Language("ndo", "ndo", Some("ng"), List("Ndonga"), List("ndonga"), List("Ndonga"))
  case object Neapolitan extends Language("nap", "nap", None, List("Neapolitan"), List("napolitain"), List("Neapel / Mundart"))
  case object NepalBhasa extends Language("new", "new", None, List("Nepal Bhasa", "Newari"), List("nepal bhasa", "newari"), List("Newari"))
  case object Nepali extends Language("nep", "nep", Some("ne"), List("Nepali"), List("népalais"), List("Nepali"))
  case object Nias extends Language("nia", "nia", None, List("Nias"), List("nias"), List("Nias-Sprache"))
  case object NigerKordofanianLanguages extends Language("nic", "nic", None, List("Niger-Kordofanian languages"), List("nigéro-kordofaniennes, langues"), List("Nigerkordofanische Sprachen (Andere)"))
  case object NiloSaharanLanguages extends Language("ssa", "ssa", None, List("Nilo-Saharan languages"), List("nilo-sahariennes, langues"), List("Nilosaharanische Sprachen (Andere)"))
  case object Niuean extends Language("niu", "niu", None, List("Niuean"), List("niué"), List("Niue-Sprache"))
  case object NoLinguisticContent extends Language("zxx", "zxx", None, List("No linguistic content", "Not applicable"), List("pas de contenu linguistique", "non applicable"), List("Kein linguistischer Inhalt"))
  case object Nogai extends Language("nog", "nog", None, List("Nogai"), List("nogaï", "nogay"), List("Nogaisch"))
  case object NorseOld extends Language("non", "non", None, List("Norse, Old"), List("norrois, vieux"), List("Altnorwegisch"))
  case object NorthAmericanIndianLanguages extends Language("nai", "nai", None, List("North American Indian languages"), List("nord-amérindiennes, langues"), List("Indianersprachen, Nordamerika (Andere)"))
  case object NorthernFrisian extends Language("frr", "frr", None, List("Northern Frisian"), List("frison septentrional"), List("Nordfriesisch"))
  case object NorthernSami extends Language("sme", "sme", Some("se"), List("Northern Sami"), List("sami du Nord"), List("Nordsaamisch"))
  case object Norwegian extends Language("nor", "nor", Some("no"), List("Norwegian"), List("norvégien"), List("Norwegisch"))
  case object NorwegianNynorsk extends Language("nno", "nno", Some("nn"), List("Norwegian Nynorsk", "Nynorsk, Norwegian"), List("norvégien nynorsk", "nynorsk, norvégien"), List("Nynorsk"))
  case object NubianLanguages extends Language("nub", "nub", None, List("Nubian languages"), List("nubiennes, langues"), List("Nubische Sprachen"))
  case object Nyamwezi extends Language("nym", "nym", None, List("Nyamwezi"), List("nyamwezi"), List("Nyamwezi-Sprache"))
  case object Nyankole extends Language("nyn", "nyn", None, List("Nyankole"), List("nyankolé"), List("Nkole-Sprache"))
  case object Nyoro extends Language("nyo", "nyo", None, List("Nyoro"), List("nyoro"), List("Nyoro-Sprache"))
  case object Nzima extends Language("nzi", "nzi", None, List("Nzima"), List("nzema"), List("Nzima-Sprache"))
  case object Occitan extends Language("oci", "oci", Some("oc"), List("Occitan (post 1500)"), List("occitan (après 1500)"), List("Okzitanisch"))
  case object OfficialAramaic extends Language("arc", "arc", None, List("Official Aramaic (700-300 BCE)", "Imperial Aramaic (700-300 BCE)"), List("araméen d'empire (700-300 BCE)"), List("Aramäisch"))
  case object Ojibwa extends Language("oji", "oji", Some("oj"), List("Ojibwa"), List("ojibwa"), List("Ojibwa-Sprache"))
  case object Oriya extends Language("ori", "ori", Some("or"), List("Oriya"), List("oriya"), List("Oriya-Sprache"))
  case object Oromo extends Language("orm", "orm", Some("om"), List("Oromo"), List("galla"), List("Galla-Sprache"))
  case object Osage extends Language("osa", "osa", None, List("Osage"), List("osage"), List("Osage-Sprache"))
  case object Ossetian extends Language("oss", "oss", Some("os"), List("Ossetian", "Ossetic"), List("ossète"), List("Ossetisch"))
  case object OtomianLanguages extends Language("oto", "oto", None, List("Otomian languages"), List("otomi, langues"), List("Otomangue-Sprachen"))
  case object Pahlavi extends Language("pal", "pal", None, List("Pahlavi"), List("pahlavi"), List("Mittelpersisch"))
  case object Palauan extends Language("pau", "pau", None, List("Palauan"), List("palau"), List("Palau-Sprache"))
  case object Pali extends Language("pli", "pli", Some("pi"), List("Pali"), List("pali"), List("Pali"))
  case object Pampanga extends Language("pam", "pam", None, List("Pampanga", "Kapampangan"), List("pampangan"), List("Pampanggan-Sprache"))
  case object Pangasinan extends Language("pag", "pag", None, List("Pangasinan"), List("pangasinan"), List("Pangasinan-Sprache"))
  case object Panjabi extends Language("pan", "pan", Some("pa"), List("Panjabi", "Punjabi"), List("pendjabi"), List("Pandschabi-Sprache"))
  case object Papiamento extends Language("pap", "pap", None, List("Papiamento"), List("papiamento"), List("Papiamento"))
  case object PapuanLanguages extends Language("paa", "paa", None, List("Papuan languages"), List("papoues, langues"), List("Papuasprachen (Andere)"))
  case object Pedi extends Language("nso", "nso", None, List("Pedi", "Sepedi", "Northern Sotho"), List("pedi", "sepedi", "sotho du Nord"), List("Pedi-Sprache"))
  case object Persian extends Language("per", "fas", Some("fa"), List("Persian"), List("persan"), List("Persisch"))
  case object PersianOld extends Language("peo", "peo", None, List("Persian, Old (ca.600-400 B.C.)"), List("perse, vieux (ca. 600-400 av. J.-C.)"), List("Altpersisch"))
  case object PhilippineLanguages extends Language("phi", "phi", None, List("Philippine languages"), List("philippines, langues"), List("Philippinisch-Austronesisch (Andere)"))
  case object Phoenician extends Language("phn", "phn", None, List("Phoenician"), List("phénicien"), List("Phönikisch"))
  case object Pohnpeian extends Language("pon", "pon", None, List("Pohnpeian"), List("pohnpei"), List("Ponapeanisch"))
  case object Polish extends Language("pol", "pol", Some("pl"), List("Polish"), List("polonais"), List("Polnisch"))
  case object Portuguese extends Language("por", "por", Some("pt"), List("Portuguese"), List("portugais"), List("Portugiesisch"))
  case object PrakritLanguages extends Language("pra", "pra", None, List("Prakrit languages"), List("prâkrit, langues"), List("Prakrit"))
  case object ProvençalOld extends Language("pro", "pro", None, List("Provençal, Old (to 1500)", "Occitan, Old (to 1500)"), List("provençal ancien (jusqu'à 1500)", "occitan ancien (jusqu'à 1500)"), List("Altokzitanisch"))
  case object Pushto extends Language("pus", "pus", Some("ps"), List("Pushto", "Pashto"), List("pachto"), List("Paschtu"))
  case object Quechua extends Language("que", "que", Some("qu"), List("Quechua"), List("quechua"), List("Quechua-Sprache"))
  case object Rajasthani extends Language("raj", "raj", None, List("Rajasthani"), List("rajasthani"), List("Rajasthani"))
  case object Rapanui extends Language("rap", "rap", None, List("Rapanui"), List("rapanui"), List("Osterinsel-Sprache"))
  case object Rarotongan extends Language("rar", "rar", None, List("Rarotongan", "Cook Islands Maori"), List("rarotonga", "maori des îles Cook"), List("Rarotonganisch"))
  case object ReservedForLocalUse extends Language("qaa", "qtz", None, List("Reserved for local use"), List("réservée à l'usage local"), List("Reserviert für lokale Verwendung"))
  case object RomanceLanguages extends Language("roa", "roa", None, List("Romance languages"), List("romanes, langues"), List("Romanische Sprachen (Andere)"))
  case object Romanian extends Language("rum", "ron", Some("ro"), List("Romanian", "Moldavian", "Moldovan"), List("roumain", "moldave"), List("Rumänisch"))
  case object Romansh extends Language("roh", "roh", Some("rm"), List("Romansh"), List("romanche"), List("Rätoromanisch"))
  case object Romany extends Language("rom", "rom", None, List("Romany"), List("tsigane"), List("Romani (Sprache)"))
  case object Rundi extends Language("run", "run", Some("rn"), List("Rundi"), List("rundi"), List("Rundi-Sprache"))
  case object Russian extends Language("rus", "rus", Some("ru"), List("Russian"), List("russe"), List("Russisch"))
  case object SalishanLanguages extends Language("sal", "sal", None, List("Salishan languages"), List("salishennes, langues"), List("Salish-Sprache"))
  case object SamaritanAramaic extends Language("sam", "sam", None, List("Samaritan Aramaic"), List("samaritain"), List("Samaritanisch"))
  case object SamiLanguages extends Language("smi", "smi", None, List("Sami languages"), List("sames, langues"), List("Saamisch"))
  case object Samoan extends Language("smo", "smo", Some("sm"), List("Samoan"), List("samoan"), List("Samoanisch"))
  case object Sandawe extends Language("sad", "sad", None, List("Sandawe"), List("sandawe"), List("Sandawe-Sprache"))
  case object Sango extends Language("sag", "sag", Some("sg"), List("Sango"), List("sango"), List("Sango-Sprache"))
  case object Sanskrit extends Language("san", "san", Some("sa"), List("Sanskrit"), List("sanskrit"), List("Sanskrit"))
  case object Santali extends Language("sat", "sat", None, List("Santali"), List("santal"), List("Santali"))
  case object Sardinian extends Language("srd", "srd", Some("sc"), List("Sardinian"), List("sarde"), List("Sardisch"))
  case object Sasak extends Language("sas", "sas", None, List("Sasak"), List("sasak"), List("Sasak"))
  case object Scots extends Language("sco", "sco", None, List("Scots"), List("écossais"), List("Schottisch"))
  case object Selkup extends Language("sel", "sel", None, List("Selkup"), List("selkoupe"), List("Selkupisch"))
  case object SemiticLanguages extends Language("sem", "sem", None, List("Semitic languages"), List("sémitiques, langues"), List("Semitische Sprachen (Andere)"))
  case object Serbian extends Language("srp", "srp", Some("sr"), List("Serbian"), List("serbe"), List("Serbisch"))
  case object Serer extends Language("srr", "srr", None, List("Serer"), List("sérère"), List("Serer-Sprache"))
  case object Shan extends Language("shn", "shn", None, List("Shan"), List("chan"), List("Schan-Sprache"))
  case object Shona extends Language("sna", "sna", Some("sn"), List("Shona"), List("shona"), List("Schona-Sprache"))
  case object SichuanYi extends Language("iii", "iii", Some("ii"), List("Sichuan Yi", "Nuosu"), List("yi de Sichuan"), List("Lalo-Sprache"))
  case object Sicilian extends Language("scn", "scn", None, List("Sicilian"), List("sicilien"), List("Sizilianisch"))
  case object Sidamo extends Language("sid", "sid", None, List("Sidamo"), List("sidamo"), List("Sidamo-Sprache"))
  case object SignLanguages extends Language("sgn", "sgn", None, List("Sign Languages"), List("langues des signes"), List("Zeichensprachen"))
  case object Siksika extends Language("bla", "bla", None, List("Siksika"), List("blackfoot"), List("Blackfoot-Sprache"))
  case object Sindhi extends Language("snd", "snd", Some("sd"), List("Sindhi"), List("sindhi"), List("Sindhi-Sprache"))
  case object Sinhala extends Language("sin", "sin", Some("si"), List("Sinhala", "Sinhalese"), List("singhalais"), List("Singhalesisch"))
  case object SinoTibetanLanguages extends Language("sit", "sit", None, List("Sino-Tibetan languages"), List("sino-tibétaines, langues"), List("Sinotibetische Sprachen (Andere)"))
  case object SiouanLanguages extends Language("sio", "sio", None, List("Siouan languages"), List("sioux, langues"), List("Sioux-Sprachen (Andere)"))
  case object SkoltSami extends Language("sms", "sms", None, List("Skolt Sami"), List("sami skolt"), List("Skoltsaamisch"))
  case object Slave extends Language("den", "den", None, List("Slave (Athapascan)"), List("esclave (athapascan)"), List("Slave-Sprache"))
  case object SlavicLanguages extends Language("sla", "sla", None, List("Slavic languages"), List("slaves, langues"), List("Slawische Sprachen (Andere)"))
  case object Slovak extends Language("slo", "slk", Some("sk"), List("Slovak"), List("slovaque"), List("Slowakisch"))
  case object Slovenian extends Language("slv", "slv", Some("sl"), List("Slovenian"), List("slovène"), List("Slowenisch"))
  case object Sogdian extends Language("sog", "sog", None, List("Sogdian"), List("sogdien"), List("Sogdisch"))
  case object Somali extends Language("som", "som", Some("so"), List("Somali"), List("somali"), List("Somali"))
  case object SonghaiLanguages extends Language("son", "son", None, List("Songhai languages"), List("songhai, langues"), List("Songhai-Sprache"))
  case object Soninke extends Language("snk", "snk", None, List("Soninke"), List("soninké"), List("Soninke-Sprache"))
  case object SorbianLanguages extends Language("wen", "wen", None, List("Sorbian languages"), List("sorabes, langues"), List("Sorbisch (Andere)"))
  case object SothoSouthern extends Language("sot", "sot", Some("st"), List("Sotho, Southern"), List("sotho du Sud"), List("Süd-Sotho-Sprache"))
  case object SouthAmericanIndianLanguages extends Language("sai", "sai", None, List("South American Indian languages"), List("sud-amérindiennes, langues"), List("Indianersprachen, Südamerika (Andere)"))
  case object SouthernAltai extends Language("alt", "alt", None, List("Southern Altai"), List("altai du Sud"), List("Altaisch"))
  case object SouthernSami extends Language("sma", "sma", None, List("Southern Sami"), List("sami du Sud"), List("Südsaamisch"))
  case object Spanish extends Language("spa", "spa", Some("es"), List("Spanish", "Castilian"), List("espagnol", "castillan"), List("Spanisch"))
  case object SrananTongo extends Language("srn", "srn", None, List("Sranan Tongo"), List("sranan tongo"), List("Sranantongo"))
  case object StandardMoroccanTamazight extends Language("zgh", "zgh", None, List("Standard Moroccan Tamazight"), List("amazighe standard marocain"), List(""))
  case object Sukuma extends Language("suk", "suk", None, List("Sukuma"), List("sukuma"), List("Sukuma-Sprache"))
  case object Sumerian extends Language("sux", "sux", None, List("Sumerian"), List("sumérien"), List("Sumerisch"))
  case object Sundanese extends Language("sun", "sun", Some("su"), List("Sundanese"), List("soundanais"), List("Sundanesisch"))
  case object Susu extends Language("sus", "sus", None, List("Susu"), List("soussou"), List("Susu"))
  case object Swahili extends Language("swa", "swa", Some("sw"), List("Swahili"), List("swahili"), List("Swahili"))
  case object Swati extends Language("ssw", "ssw", Some("ss"), List("Swati"), List("swati"), List("Swasi-Sprache"))
  case object Swedish extends Language("swe", "swe", Some("sv"), List("Swedish"), List("suédois"), List("Schwedisch"))
  case object SwissGerman extends Language("gsw", "gsw", None, List("Swiss German", "Alemannic", "Alsatian"), List("suisse alémanique", "alémanique", "alsacien"), List("Schweizerdeutsch"))
  case object Syriac extends Language("syr", "syr", None, List("Syriac"), List("syriaque"), List("Neuostaramäisch"))
  case object Tagalog extends Language("tgl", "tgl", Some("tl"), List("Tagalog"), List("tagalog"), List("Tagalog"))
  case object Tahitian extends Language("tah", "tah", Some("ty"), List("Tahitian"), List("tahitien"), List("Tahitisch"))
  case object TaiLanguages extends Language("tai", "tai", None, List("Tai languages"), List("tai, langues"), List("Thaisprachen (Andere)"))
  case object Tajik extends Language("tgk", "tgk", Some("tg"), List("Tajik"), List("tadjik"), List("Tadschikisch"))
  case object Tamashek extends Language("tmh", "tmh", None, List("Tamashek"), List("tamacheq"), List("Tamašeq"))
  case object Tamil extends Language("tam", "tam", Some("ta"), List("Tamil"), List("tamoul"), List("Tamil"))
  case object Tatar extends Language("tat", "tat", Some("tt"), List("Tatar"), List("tatar"), List("Tatarisch"))
  case object Telugu extends Language("tel", "tel", Some("te"), List("Telugu"), List("télougou"), List("Telugu-Sprache"))
  case object Tereno extends Language("ter", "ter", None, List("Tereno"), List("tereno"), List("Tereno-Sprache"))
  case object Tetum extends Language("tet", "tet", None, List("Tetum"), List("tetum"), List("Tetum-Sprache"))
  case object Thai extends Language("tha", "tha", Some("th"), List("Thai"), List("thaï"), List("Thailändisch"))
  case object Tibetan extends Language("tib", "bod", Some("bo"), List("Tibetan"), List("tibétain"), List("Tibetisch"))
  case object Tigre extends Language("tig", "tig", None, List("Tigre"), List("tigré"), List("Tigre-Sprache"))
  case object Tigrinya extends Language("tir", "tir", Some("ti"), List("Tigrinya"), List("tigrigna"), List("Tigrinja-Sprache"))
  case object Timne extends Language("tem", "tem", None, List("Timne"), List("temne"), List("Temne-Sprache"))
  case object Tiv extends Language("tiv", "tiv", None, List("Tiv"), List("tiv"), List("Tiv-Sprache"))
  case object Tlingit extends Language("tli", "tli", None, List("Tlingit"), List("tlingit"), List("Tlingit-Sprache"))
  case object TokPisin extends Language("tpi", "tpi", None, List("Tok Pisin"), List("tok pisin"), List("Neumelanesisch"))
  case object Tokelau extends Language("tkl", "tkl", None, List("Tokelau"), List("tokelau"), List("Tokelauanisch"))
  case object Tonga extends Language("tog", "tog", None, List("Tonga (Nyasa)"), List("tonga (Nyasa)"), List("Tonga (Bantusprache, Sambia)"))
  case object TongaIslands extends Language("ton", "ton", Some("to"), List("Tonga (Tonga Islands)"), List("tongan (Îles Tonga)"), List("Tongaisch"))
  case object Tsimshian extends Language("tsi", "tsi", None, List("Tsimshian"), List("tsimshian"), List("Tsimshian-Sprache"))
  case object Tsonga extends Language("tso", "tso", Some("ts"), List("Tsonga"), List("tsonga"), List("Tsonga-Sprache"))
  case object Tswana extends Language("tsn", "tsn", Some("tn"), List("Tswana"), List("tswana"), List("Tswana-Sprache"))
  case object Tumbuka extends Language("tum", "tum", None, List("Tumbuka"), List("tumbuka"), List("Tumbuka-Sprache"))
  case object TupiLanguages extends Language("tup", "tup", None, List("Tupi languages"), List("tupi, langues"), List("Tupi-Sprache"))
  case object Turkish extends Language("tur", "tur", Some("tr"), List("Turkish"), List("turc"), List("Türkisch"))
  case object TurkishOttoman extends Language("ota", "ota", None, List("Turkish, Ottoman (1500-1928)"), List("turc ottoman (1500-1928)"), List("Osmanisch"))
  case object Turkmen extends Language("tuk", "tuk", Some("tk"), List("Turkmen"), List("turkmène"), List("Turkmenisch"))
  case object Tuvalu extends Language("tvl", "tvl", None, List("Tuvalu"), List("tuvalu"), List("Elliceanisch"))
  case object Tuvinian extends Language("tyv", "tyv", None, List("Tuvinian"), List("touva"), List("Tuwinisch"))
  case object Twi extends Language("twi", "twi", Some("tw"), List("Twi"), List("twi"), List("Twi-Sprache"))
  case object Udmurt extends Language("udm", "udm", None, List("Udmurt"), List("oudmourte"), List("Udmurtisch"))
  case object Ugaritic extends Language("uga", "uga", None, List("Ugaritic"), List("ougaritique"), List("Ugaritisch"))
  case object Uighur extends Language("uig", "uig", Some("ug"), List("Uighur", "Uyghur"), List("ouïgour"), List("Uigurisch"))
  case object Ukrainian extends Language("ukr", "ukr", Some("uk"), List("Ukrainian"), List("ukrainien"), List("Ukrainisch"))
  case object Umbundu extends Language("umb", "umb", None, List("Umbundu"), List("umbundu"), List("Mbundu-Sprache"))
  case object UncodedLanguages extends Language("mis", "mis", None, List("Uncoded languages"), List("langues non codées"), List("Einzelne andere Sprachen"))
  case object Undetermined extends Language("und", "und", None, List("Undetermined"), List("indéterminée"), List("Nicht zu entscheiden"))
  case object UpperSorbian extends Language("hsb", "hsb", None, List("Upper Sorbian"), List("haut-sorabe"), List("Obersorbisch"))
  case object Urdu extends Language("urd", "urd", Some("ur"), List("Urdu"), List("ourdou"), List("Urdu"))
  case object Uzbek extends Language("uzb", "uzb", Some("uz"), List("Uzbek"), List("ouszbek"), List("Usbekisch"))
  case object Vai extends Language("vai", "vai", None, List("Vai"), List("vaï"), List("Vai-Sprache"))
  case object Venda extends Language("ven", "ven", Some("ve"), List("Venda"), List("venda"), List("Venda-Sprache"))
  case object Vietnamese extends Language("vie", "vie", Some("vi"), List("Vietnamese"), List("vietnamien"), List("Vietnamesisch"))
  case object Volapük extends Language("vol", "vol", Some("vo"), List("Volapük"), List("volapük"), List("Volapük"))
  case object Votic extends Language("vot", "vot", None, List("Votic"), List("vote"), List("Wotisch"))
  case object WakashanLanguages extends Language("wak", "wak", None, List("Wakashan languages"), List("wakashanes, langues"), List("Wakash-Sprachen"))
  case object Walloon extends Language("wln", "wln", Some("wa"), List("Walloon"), List("wallon"), List("Wallonisch"))
  case object Waray extends Language("war", "war", None, List("Waray"), List("waray"), List("Waray"))
  case object Washo extends Language("was", "was", None, List("Washo"), List("washo"), List("Washo-Sprache"))
  case object Welsh extends Language("wel", "cym", Some("cy"), List("Welsh"), List("gallois"), List("Kymrisch"))
  case object WesternFrisian extends Language("fry", "fry", Some("fy"), List("Western Frisian"), List("frison occidental"), List("Friesisch"))
  case object Wolaitta extends Language("wal", "wal", None, List("Wolaitta", "Wolaytta"), List("wolaitta", "wolaytta"), List("Walamo-Sprache"))
  case object Wolof extends Language("wol", "wol", Some("wo"), List("Wolof"), List("wolof"), List("Wolof-Sprache"))
  case object Xhosa extends Language("xho", "xho", Some("xh"), List("Xhosa"), List("xhosa"), List("Xhosa-Sprache"))
  case object Yakut extends Language("sah", "sah", None, List("Yakut"), List("iakoute"), List("Jakutisch"))
  case object Yao extends Language("yao", "yao", None, List("Yao"), List("yao"), List("Yao-Sprache (Bantusprache)"))
  case object Yapese extends Language("yap", "yap", None, List("Yapese"), List("yapois"), List("Yapesisch"))
  case object Yiddish extends Language("yid", "yid", Some("yi"), List("Yiddish"), List("yiddish"), List("Jiddisch"))
  case object Yoruba extends Language("yor", "yor", Some("yo"), List("Yoruba"), List("yoruba"), List("Yoruba-Sprache"))
  case object YupikLanguages extends Language("ypk", "ypk", None, List("Yupik languages"), List("yupik, langues"), List("Ypik-Sprachen"))
  case object ZandeLanguages extends Language("znd", "znd", None, List("Zande languages"), List("zandé, langues"), List("Zande-Sprachen"))
  case object Zapotec extends Language("zap", "zap", None, List("Zapotec"), List("zapotèque"), List("Zapotekisch"))
  case object Zaza extends Language("zza", "zza", None, List("Zaza", "Dimili", "Dimli", "Kirdki", "Kirmanjki", "Zazaki"), List("zaza", "dimili", "dimli", "kirdki", "kirmanjki", "zazaki"), List("Zazaki"))
  case object Zenaga extends Language("zen", "zen", None, List("Zenaga"), List("zenaga"), List("Zenaga"))
  case object Zhuang extends Language("zha", "zha", Some("za"), List("Zhuang", "Chuang"), List("zhuang", "chuang"), List("Zhuang"))
  case object Zulu extends Language("zul", "zul", Some("zu"), List("Zulu"), List("zoulou"), List("Zulu-Sprache"))
  case object Zuni extends Language("zun", "zun", None, List("Zuni"), List("zuni"), List("Zuñi-Sprache"))

  private def init(l: Language) = synchronized {
    lookup += l.terminology -> l
    lookup += l.bibliographic -> l
    l.iso639_1 match {
      case Some(v) => lookup += v.toLowerCase -> l
      case None => // Ignore
    }
    (l.englishNames ::: l.frenchNames ::: l.germanNames).foreach {
      case n => lookup += n.toLowerCase -> l
    }
  }

  def get(name: String, caseSensitive: Boolean) = lookup.get(name.toLowerCase)

  val values = findValues.toVector
}